name = "Ravishankar Haranath"
avatar = "images/profile.png"                                                              # Avatar image. Default to "images/profile.webp".
bio = "Ubuntu, RHEL, JS/Node, Java-SE, Golang, Cloud and DevOps"
company = "Solutions with FOSS"
location = "<a href='https://goo.gl/maps/xw3V1iacBnY3JNRW6' target='_blank'>Bengaluru</a>"

# alternatives:
# location = "<a href='https://www.openstreetmap.org/search?query=Earth'>Earth</a>"
# location = "<a href='https://www.google.com/maps/search/Earth'>Earth</a>"
# about = "https://domain.tld" # The external about page. The internal about page will be used if not set.

[params]
#layout = "compact"
