[en]
languageName = "English"
weight = 1
contentDir = "content/en"

[kn]
languageName = "ಕನ್ನಡ"
weight = 2
contentDir = "content/kn"

[kn.params]
description = "ನನ್ನ ಕನ್ನಡ ಲೇಖನಗಳ ಸಂಗ್ರಹ"
keywords = "Hugo, Bootstrap, Thème Blog"
