[[main]]
name = "LinkedIn"
identifier = "linkedin"
pre = '<i class="fab fa-fw fa-linkedin-in"></i>'
url = "https://linkedin.com/in/raviharanath/"
weight = 99
[[main]]
name = "Github"
identifier = "github"
pre = '<i class="fab fa-fw fa-github"></i>'
url = "https://github.com/ravihara"
weight = 100
